routes/web.php
<?php


Route::get('/', 'HomeController@index')->name('home');

/*
 * auth routes
 */
Auth::routes();



Route::view('/faq', 'staticpages.faq')->name('static.faq');
Route::view('/usloviq', 'staticpages.usloviq')->name('static.usloviq');
Route::view('/contact', 'staticpages.contact')->name('static.contact');






Route::get('/blog', 'ArticleController@index')->name('articles.index');
Route::get('/blog/{id}/{slug}/', 'ArticleController@single')->name('articles.single');
Route::get('/blog/category/{id}/{slug}', 'CategoryController@single')->name('category.single');


Route::get('theme/{themename}', 'ThemeController@switchtheme')->name('theme.switch');


Route::get('users/{id}', 'UserController@single')->name('users.single');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('changepassword', 'UserController@changepassword')->name('users.changepassword');
Route::post('updatepassword', 'UserController@updatepassword')->name('users.updatepassword');
Route::get('users/{id}/edit', 'UserController@edit')->name('users.edit')->middleware('auth');
Route::post('users/{id}/update', 'UserController@update')->name('users.update')->middleware('auth');
Route::get('users/check/{id}', 'UserController@check')->name('users.check')->middleware('auth');
Route::post('users/checkpost/{id}', 'UserController@checkpost')->name('users.checkpost')->middleware('auth');




Route::get('securitytoken/{user_id}', 'SecureTokenController@single')->name('securetoken.single')->middleware('auth');
Route::get('generatetoken', 'SecureTokenController@create')->name('securetoken.create')->middleware('auth');
Route::get('user/securetokens', 'SecureTokenController@index')->name('securetoken.index')->middleware('auth');
Route::get('user/securetokens/{id}', 'SecureTokenController@show')->name('securetoken.show')->middleware('auth');
Route::post('generatetoken/refresh/{id}', 'SecureTokenController@destroy')->name('securetoken.delete')->middleware('auth');
Route::post('generatetoken', 'SecureTokenController@store')->name('securetoken.store')->middleware('auth');




Route::get('addreputation/{receiverid}', 'ReputationController@create')->name('reputation.create')->middleware('auth');
Route::post('addreputation/check/{receiverid}', 'ReputationController@check')->name('reputation.check')->middleware('auth');
Route::get('reputationtracking/next/{receiver}', 'ReputationController@next')->name('reputation.next')->middleware('auth');
Route::post('reputationsave/{receiverid}', 'ReputationController@save')->name('reputation.save')->middleware('auth');



Route::get('reputation/{receiver}', 'ReputationController@finaldata')->name('reputation.submit')->middleware
('auth');
Route::get('viewreputation/{id}', 'ReputationController@single')->name('reputation.single');


/*
 * Search Routes
 */
Route::get('search', 'SearchController@index')->name('search.index');
Route::post('search', 'SearchController@searchpost')->name('search.searchpost');
Route::get('search/results/{results}/{searchterm}', 'SearchController@searchresults')->name('search.results');




/*
 * Admin Routes / Resource types - aka: automatic index/edit/single/delete -> dont touch if you are not well aware of
 *  the REST concept and how Laravel handles them
 * tldr: we group /panel/ routes by middleware IsAdmin, and their route name starts with admin.
 */

Route::namespace('Admin')->middleware('IsAdmin')->prefix('panel')->name('admin.')->group(function () {

    Route::view('/', 'admin.layouts.app');


    Route::resource('users','UserController');
    Route::resource('articles','ArticleController');
    Route::resource('category','CategoryController');
    Route::resource('reputations','ReputationController');
    Route::resource('userinfo','UserInfoController');

});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    public function category() {
        return $this->belongsTo('App\Category');
    }


    public function urlslug() {
        return url('/blog/'.$this->id . '/' . $this->slug);
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Article;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Category;
use Illuminate\Support\Str;
use App\Traits\UploadTrait;
use Intervention\Image\Facades\Image;

class ArticleController extends Controller
{
    use UploadTrait;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::with('category')->orderBy('created_at','desc')->get();

        return view('admin.article.index',compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();

        return view('admin.article.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(!$request['category_id']) {
            return back()->with('error','Няма избрана категория!');
        }

        else {
            $article = new Article();

            $article->title = $request['title'];
            $article->slug = Str::slug($request['title'],'-');
            $article->body = $request['body'];
            if($request['is_image']) {

                if ($request->has('image')) {
                    // Get image file
                    $image = $request->file('image');
                    // Make a image name based on user name and current timestamp
                    $name = $request->input('image') .time();
                    // Define folder path
                    $folder = 'articleimages';
                    // Make a file path where image will be stored [ folder path + file name + file extension]
                    $filePath = $folder . $name. '.' . $image->getClientOriginalExtension();
                    // Upload image
                    $uploaded =  $this->uploadOne($image, $folder, 'public_uploads', $name);
//                $file_path = Storage::url($uploaded);
//                    $path = Storage::disk('public_uploads')->path($uploaded);



                    Image::make( $image->getRealPath() )->fit(750, 350)
                        ->save('uploads/articleimages/'. $name . '.' .$image
                                ->getClientOriginalExtension());
                    ;

                    $article->image_path = $uploaded;
                    $article->image_name = $name . '.' .$image->getClientOriginalExtension();

                }
            }
            $article->category_id = $request['category_id'];
            $article->save();

            return redirect()->route('admin.articles.index')->with('success','Статията е успешно добавена');

        }

    }



    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::find($id);
        $categories = Category::all();

        return view('admin.article.edit',compact('article','categories'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $article = Article::find($id);

        $article->title = $request['title'];
        $article->slug = $request['slug'];
        $article->body = $request['body'];
        if($request['is_image']) {

            if ($request->has('image')) {
                // Get image file
                $image = $request->file('image');
                // Make a image name based on user name and current timestamp
                $name = $request->input('image') .time();
                // Define folder path
                $folder = 'articleimages';
                // Make a file path where image will be stored [ folder path + file name + file extension]
                $filePath = $folder . $name. '.' . $image->getClientOriginalExtension();
                // Upload image
                $uploaded =  $this->uploadOne($image, $folder, 'public_uploads', $name);
//                $file_path = Storage::url($uploaded);
//                    $path = Storage::disk('public_uploads')->path($uploaded);



                Image::make( $image->getRealPath() )->fit(900, 200)
                    ->save('uploads/articleimages/'. $name . '.' .$image
                            ->getClientOriginalExtension());
                ;

                $article->image_path = $uploaded;
                $article->image_name = $name . '.' .$image->getClientOriginalExtension();

            }
        }
        $article->category_id = $request['category_id'];
        $article->save();

        return redirect()->route('admin.articles.index')->with('success','Статията е успешно редактирана');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::with('category')->orderBy('created_at','desc')->get();


        return view('blog.index',compact('articles'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function single($id,$slug)
    {
        $article = Article::find($id);
        if(!$article) {
            return redirect()->route('blog.index')->with('error','Статията не е намерена');
        }

        else {
            $article->views ++;
            $article->save();
            return view('blog.single',compact('article'));
        }


    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Article $article)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        //
    }
}

resources/views/admin/article/create.blade.php
@extends('admin.layouts.app')

@section('title','Добавяне на нова Статия')

@section('content')

    <h5 class="mb-2">Нова Статия</h5>

    <div class="card-body">
        <form action="{{route('admin.articles.store')}}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-lg-12">
                    @method('post')


                    <div class="card card-success">
                        <div class="card-header">
                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                                        class="fas fa-minus"></i></button>
                                <button type="button" class="btn btn-tool"
                                        data-card-widget="remove"><i class="fas fa-times"></i></button>
                            </div>
                            <h3 class="card-title">Обща Информация</h3>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <small>Заглавие</small>
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" value=""
                                               name="title">

                                    </div>
                                </div>

                                <div class="col-lg-6">
                                    <p>SLUG - генерира се автоматично от тайтъла -   после може да се редактира </p>
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" value=""
                                               name="slug" disabled>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label> Категория / задължително е да има категория заради
                                                    slug-a който depend-ва на категориите!</label>
                                                <select class="form-control" name="category_id">
                                                    @forelse($categories as $category)
                                                            <option value="{{$category->id}}">{{$category->name}}</option>
                                                    @empty
                                                    @endforelse
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label> Текст<span
                                                        class="small"></span></label>
                                                <textarea class="form-control" rows="22" cols="10" name="body"
                                                          id="body"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Заглавно Изобр?</label>
                                <select class="form-control" name="is_image">
                                    <option value="0" selected>Не</option>
                                    <option value="1">Да</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <div class="form-group">
                                <label for="exampleInputFile">Изображение</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" name="image"
                                               id="exampleInputFile">
                                        <label class="custom-file-label" for="exampleInputFile">Файл</label>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <hr>
                        <button type="submit" class="btn btn-block btn-info btn-lg">Добавяне на Статия</button>
                    </div>
                </div>

            </div>
        </form>

    </div>

@stop



@section('scripts')
    <script src="{{asset('admin/plugins/select2/js/select2.full.min.js')}}"></script>
    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2({
                theme: 'bootstrap4'
            });
            $('#tags').select2({
                theme: 'bootstrap4',
                tags: true,
                // data: ["Clare","Cork","South Dublin"],
                tokenSeparators: [','],

                /* the next 2 lines make sure the user can click away after typing and not lose the new tag */

            });
        });



    </script>
    <script src="{{asset('tinymce/tinymce.min.js')}}"></script>
    <script>
        tinymce.init({
            selector: 'textarea',
            height: 500,
            menubar: true,
            plugins: [
                'advlist autolink lists link  charmap print preview anchor textcolor',
                'searchreplace visualblocks code fullscreen',
                'insertdatetime media table contextmenu paste code help wordcount codesample', 'code image'
            ],
            toolbar: 'image code | codesample | insert | undo redo |  formatselect | bold italic backcolor  | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help',
            content_css: [
                '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
                '//www.tinymce.com/css/codepen.min.css'],




        });
        let img = tinymce.selection.getNode();


    </script>

@endsection


@section('css')
    <link rel="stylesheet" href="{{asset('admin/plugins/select2/css/select2.min.css')}}">
    <link rel="stylesheet" href="{{asset('admin/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
    <style>
        .select2-results__option[aria-selected=true] {
            display: none;
        }
    </style>

@endsection

resources/views/admin/article/edit.blade.php
@extends('admin.layouts.app')

@section('title','Добавяне на нова Статия')

@section('content')

    <h5 class="mb-2">Нова Статия</h5>

    <div class="card-body">
        <form action="{{route('admin.articles.update',$article->id)}}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-lg-12">
                    @method('put')


                    <div class="card card-success">
                        <div class="card-header">
                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                                        class="fas fa-minus"></i></button>
                                <button type="button" class="btn btn-tool"
                                        data-card-widget="remove"><i class="fas fa-times"></i></button>
                            </div>
                            <h3 class="card-title">Обща Информация</h3>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <small>Заглавие</small>
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" value="{{$article->title}}"
                                               name="title">

                                    </div>
                                </div>

                                <div class="col-lg-6">
                                    <p>SLUG  </p>
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" value="{{$article->slug}}"
                                               name="slug">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label> Категория / задължително е да има категория заради
                                                    slug-a който depend-ва на категориите!</label>
                                                <select class="form-control" name="category_id">
                                                    @forelse($categories as $cat)
                                                        <option value="{{$cat->id}}"
                                                            {{$cat->id == $article->category->id ? 'selected' : ''
                                                            }}>{{$cat->name}}</option>
                                                    @empty
                                                    @endforelse
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label> Текст<span
                                                        class="small"></span></label>
                                                <textarea class="form-control" rows="22" cols="10" name="body"
                                                          id="body">{{$article->body}}</textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label>Заглавно Изобр?</label>
                                <select class="form-control" name="is_image">
                                    <option value="0" selected>Не</option>
                                    <option value="1">Да</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <div class="form-group">
                                <label for="exampleInputFile">Смяна на Изображение</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" name="image"
                                               id="exampleInputFile">
                                        <label class="custom-file-label" for="exampleInputFile">Файл</label>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <hr>
                        <button type="submit" class="btn btn-block btn-info btn-lg">Редакция на Статия</button>
                    </div>
                </div>

            </div>
        </form>

    </div>

@stop



@section('scripts')
    <script src="{{asset('admin/plugins/select2/js/select2.full.min.js')}}"></script>
    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2({
                theme: 'bootstrap4'
            });
            $('#tags').select2({
                theme: 'bootstrap4',
                tags: true,
                // data: ["Clare","Cork","South Dublin"],
                tokenSeparators: [','],

                /* the next 2 lines make sure the user can click away after typing and not lose the new tag */

            });
        });



    </script>
    <script src="{{asset('tinymce/tinymce.min.js')}}"></script>
    <script>
        tinymce.init({
            selector: 'textarea',
            height: 500,
            menubar: true,
            plugins: [
                'advlist autolink lists link  charmap print preview anchor textcolor',
                'searchreplace visualblocks code fullscreen',
                'insertdatetime media table contextmenu paste code help wordcount codesample', 'code image'
            ],
            toolbar: 'image code | codesample | insert | undo redo |  formatselect | bold italic backcolor  | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help',
            content_css: [
                '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
                '//www.tinymce.com/css/codepen.min.css'],




        });
        let img = tinymce.selection.getNode();


    </script>

@endsection


@section('css')
    <link rel="stylesheet" href="{{asset('admin/plugins/select2/css/select2.min.css')}}">
    <link rel="stylesheet" href="{{asset('admin/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
    <style>
        .select2-results__option[aria-selected=true] {
            display: none;
        }
    </style>

@endsection

resources/views/admin/article/index.blade.php
@extends('admin.layouts.app')
@section('title','Статии')

@section('content')
    <div class="card-body table-responsive p-0">
        <a href="{{route('admin.articles.create')}}">
            <button type="button" class="btn btn-info btn-sm">Добавяне на Нова Статия</button>
        </a>
        <hr>
        <table class="table table-hover">
            <tbody>
            <tr>
                <th>ID</th>
                <th>Име</th>

                <th> Категория</th>
                <th>Прегледа</th>
                <th>Дата</th>
                <th>Опции</th>
            </tr>
            @forelse($articles as $article)
                <tr class="">
                    <td>{{$article->id}}</td>
                    <td>{{\Illuminate\Support\Str::limit($article->title,22)}}</td>

                    <td>{{$article->category ? $article->category->name : 'НЯМА'}}</td>
                    <td>
                        {{$article->views}}
                    </td>
                    <td>{{$article->created_at}}</td>


                    <td>
                        <a href="{{route('admin.articles.edit', $article->id)}}"><button class="btn
                        btn-primary
                        btn-sm">Редакция</button></a>
                        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal"
                                data-target="#modal-danger-{{$article->id}}">
                            Изтриване
                        </button>
                    </td>
                </tr>
                <div class="modal fade" id="modal-danger-{{$article->id}}">
                    <div class="modal-dialog">
                        <div class="modal-content bg-danger">
                            <div class="modal-header">
                                <h4 class="modal-title">Изтриване на Статия?</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <div class="modal-footer justify-content-between">
                                <form action="{{route('admin.articles.destroy',$article->id)}}" method="POST">
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="btn btn-danger">Изтриване</button>
                                </form>
                                <button type="button" class="btn btn-outline-light" data-dismiss="modal">Отказ</button>
                            </div>
                        </div>
                        <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>

            @empty
                <hr>
                Няма добавени Статии Все още.
            @endforelse
            </tbody>
        </table>
    </div>
    <!-- /.modal -->
@stop