routes/web.php
<?php


Route::get('/', 'HomeController@index')->name('home');

/*
 * auth routes
 */
Auth::routes();



Route::view('/faq', 'staticpages.faq')->name('static.faq');
Route::view('/usloviq', 'staticpages.usloviq')->name('static.usloviq');
Route::view('/contact', 'staticpages.contact')->name('static.contact');






Route::get('/blog', 'ArticleController@index')->name('articles.index');
Route::get('/blog/{id}/{slug}/', 'ArticleController@single')->name('articles.single');
Route::get('/blog/category/{id}/{slug}', 'CategoryController@single')->name('category.single');


Route::get('theme/{themename}', 'ThemeController@switchtheme')->name('theme.switch');


Route::get('users/{id}', 'UserController@single')->name('users.single');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('changepassword', 'UserController@changepassword')->name('users.changepassword');
Route::post('updatepassword', 'UserController@updatepassword')->name('users.updatepassword');
Route::get('users/{id}/edit', 'UserController@edit')->name('users.edit')->middleware('auth');
Route::post('users/{id}/update', 'UserController@update')->name('users.update')->middleware('auth');
Route::get('users/check/{id}', 'UserController@check')->name('users.check')->middleware('auth');
Route::post('users/checkpost/{id}', 'UserController@checkpost')->name('users.checkpost')->middleware('auth');




Route::get('securitytoken/{user_id}', 'SecureTokenController@single')->name('securetoken.single')->middleware('auth');
Route::get('generatetoken', 'SecureTokenController@create')->name('securetoken.create')->middleware('auth');
Route::get('user/securetokens', 'SecureTokenController@index')->name('securetoken.index')->middleware('auth');
Route::get('user/securetokens/{id}', 'SecureTokenController@show')->name('securetoken.show')->middleware('auth');
Route::post('generatetoken/refresh/{id}', 'SecureTokenController@destroy')->name('securetoken.delete')->middleware('auth');
Route::post('generatetoken', 'SecureTokenController@store')->name('securetoken.store')->middleware('auth');




Route::get('addreputation/{receiverid}', 'ReputationController@create')->name('reputation.create')->middleware('auth');
Route::post('addreputation/check/{receiverid}', 'ReputationController@check')->name('reputation.check')->middleware('auth');
Route::get('reputationtracking/next/{receiver}', 'ReputationController@next')->name('reputation.next')->middleware('auth');
Route::post('reputationsave/{receiverid}', 'ReputationController@save')->name('reputation.save')->middleware('auth');



Route::get('reputation/{receiver}', 'ReputationController@finaldata')->name('reputation.submit')->middleware
('auth');
Route::get('viewreputation/{id}', 'ReputationController@single')->name('reputation.single');


/*
 * Search Routes
 */
Route::get('search', 'SearchController@index')->name('search.index');
Route::post('search', 'SearchController@searchpost')->name('search.searchpost');
Route::get('search/results/{results}/{searchterm}', 'SearchController@searchresults')->name('search.results');




/*
 * Admin Routes / Resource types - aka: automatic index/edit/single/delete -> dont touch if you are not well aware of
 *  the REST concept and how Laravel handles them
 * tldr: we group /panel/ routes by middleware IsAdmin, and their route name starts with admin.
 */

Route::namespace('Admin')->middleware('IsAdmin')->prefix('panel')->name('admin.')->group(function () {

    Route::view('/', 'admin.layouts.app');


    Route::resource('users','UserController');
    Route::resource('articles','ArticleController');
    Route::resource('category','CategoryController');
    Route::resource('reputations','ReputationController');
    Route::resource('userinfo','UserInfoController');

});

app/Reputation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reputation extends Model
{


    public function receiver() {
        return $this->belongsTo('App\User','receiver_id');
    }

    public function sender() {
        return $this->belongsTo('App\User','sender_id');
    }

    public function token() {
        return $this->belongsTo('App\SecureToken','secure_token_id');

    }
}

app/Http/Controllers/Admin/ReputationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Reputation;
use Illuminate\Http\Request;

class ReputationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $reputations = Reputation::with('receiver','sender','token')->paginate(10);

        return view('admin.reputations.index',compact('reputations'));


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $reputation = Reputation::find($id);

        return view('admin.reputations.edit',compact('reputation'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {


        $reputation = Reputation::find($id);

        $reputation->trackingcode = $request['trackingcode'];

       $reputation->is_negative = $request['is_negative'];
       $reputation->is_active = $request['is_active'];

        $reputation->save();


        return redirect()->route('admin.reputations.index')->with('success','Репутацията е Редактирана');




    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $reputation = Reputation::find($id);
        $reputation->delete();

        return redirect()->route('admin.reputations.index')->with('success','Репутацията е Изтрита');
    }
}

app/Http/Controllers/ReputationController.php
<?php

namespace App\Http\Controllers;

use App\Reputation;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\User;
use App\SecureToken;
use TheSeer\Tokenizer\Token;

class ReputationController extends Controller
{


    public function single($id) {

        $reputation = Reputation::find($id);
        if($reputation && $reputation->is_active) {

            if (Auth::check() && Auth::user()->id == $reputation->receiver_id) {
                $reputation->is_seen = true;
                $reputation->save();
            }

            return view('reputation.single',compact('reputation'));

        }
        else {
            return redirect('/')->with('error','Невалидна Страница');
        }


    }



    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($receiverid)
    {
        $user = User::find($receiverid);

        if(!$user) {
            return redirect()->back()->with('error','Невалиден Потребител');
        }


        return view('reputation.next',compact('user'));
    }





    public function finaldata($receiver) {



        $receiver = User::find($receiver);

        if(!$receiver) {
            return back()->with('error','Такъв потребител не съществува');

        }

        if($receiver->is_merchant) {
            return back()->with('error','Не можете да оставяте репутация на търговци');
        }
        return view('reputation.finaldata',compact('receiver'));
    }



    public function save(Request $request,$receiverid) {

        if(! $request['trackingcode']) {
            return redirect()->back()->with('error','Моля Въведете Номер на Товарителница');

        }

        if(!$request['securecode']) {
            return redirect()->back()->with('error','Моля Въведете код');

        }
        else {
            $validatedData = $request->validate([
                'securecode' => 'required|min:100000|max:999999|integer',

            ],
                [
                    'securecode.*' => 'Неправилен формат на кода - Моля използвайте само 6 цифри'
                ]);

            $receiver = User::find($receiverid);
            if ($receiver->tokens()->exists()) {
                $usertokens = $receiver->tokens;
                $isvalid = false;
                $isused = false;

                foreach ($usertokens as $token) { // foreach all securecodes of the provided user and check if its
                    // valid code or not
                    if($token->code == $validatedData['securecode']) {
                        $isvalid = true;
                        break;
                    }
                }





                if ($isvalid) { //  code is 100% valid and usable for a reputation
                    $token = SecureToken::where('code',$validatedData['securecode'])->first();

                    if($token->is_used) {
                        return redirect()->back()->with('error','Кода е Неактивен или Използван Вече');
                    }

                    $reputation = new Reputation(); //  add a new reputation
                    if($request['is_negative']) {
                        $reputation->is_negative = true;

                    }
                    $reputation->trackingcode = $request['trackingcode'];
                    $reputation->receiver_id = $receiverid;
                    $reputation->sender_id = Auth::user()->id;

                    $token->is_used = true;
                    $token->save();


                    $reputation->secure_token_id = $token->id;


                        // assign reputation to users model
                   if ($request['is_negative'])
                   {
                       $receiver->negativecount ++;

                   }
                   else {
                       $receiver->positivecount ++;
                   }
                   $receiver->save();


                    $reputation->save();

                    return redirect()->route('users.single',$receiverid)->with('success','Успешно Добавихте Репутация на потребителя');


                }
                else { //  user have code, but its not valid
                    return redirect()->back()->with('error', 'Кода е невалиден');
                }
            } // user doesnt have any secure codes, so throw an error
            else {
                return redirect()->back()->with('error', 'Потребителят все още не е генерирал своят код за сигурност');

            }
        }

    }

}

resources/views/admin/reputations/edit.blade.php
@extends('admin.layouts.app')

@section('title','Редакция на Репутация')

@section('content')

    <h5 class="mb-2">Редакция на Репутация: {{$reputation->id}}</h5>

    <div class="card-body">
        <form action="{{route('admin.reputations.update',$reputation->id)}}" method="POST"
              enctype="multipart/form-data">

            <div class="row">
                <div class="col-lg-12">
                    @method('put')
                    @csrf

                    <div class="card card-success">
                        <div class="card-header">
                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                                        class="fas fa-minus"></i></button>
                                <button type="button" class="btn btn-tool"
                                        data-card-widget="remove"><i class="fas fa-times"></i></button>
                            </div>
                            <h3 class="card-title">Обща Информация</h3>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <p>Активна?</p>
                                    <div class="form-group">

                                        <select class="form-control" name="is_active">

                                            <option value="1" {{$reputation->is_active ? 'selected' : ''}}>Да</option>
                                            <option value="0"  {{$reputation->is_active ? '' : 'selected'}}>Не</option>

                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <small>Получател {!! $reputation->receiver->textrepcount() !!}</small>
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" value="{{$reputation->receiver->name}}"
                                               name="receiver" disabled>

                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <small>Изпращач {!! $reputation->sender->textrepcount() !!}</small>
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" value="{{$reputation->sender->name}}"
                                               name="sender" disabled>

                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <small>Номер На Пратка</small>
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" value="{{$reputation->trackingcode}}"
                                               name="trackingcode">

                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <p>Репутация Тип:</p>
                                    <div class="form-group">

                                        <select class="form-control" name="is_negative">

                                            <option value="1" {{$reputation->is_negative ?
                                            'selected' : ''}}>Отрицателна</option>
                                            <option value="0" {{$reputation->is_negative ? '' :
                                            'selected'}}>Положителна</option>

                                        </select>
                                    </div>
                                </div>

                                </div>

                            </div>
                        </div>
                        <hr>
                        <button type="submit" class="btn btn-block btn-info btn-lg">Редакция</button>
                    </div>
                </div>

            </div>
        </form>

    </div>

@stop



@section('scripts')
    <script src="{{asset('admin/plugins/select2/js/select2.full.min.js')}}"></script>
    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2({
                theme: 'bootstrap4'
            })});


    </script>
    <script src="{{asset('tinymce/tinymce.min.js')}}"></script>
    <script>tinymce.init({selector:'#body'});</script>

@endsection


@section('css')
    <link rel="stylesheet" href="{{asset('admin/plugins/select2/css/select2.min.css')}}">
    <link rel="stylesheet" href="{{asset('admin/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
    <style>
        .select2-results__option[aria-selected=true] {
            display: none;
        }
    </style>

@endsection

resources/views/admin/reputations/index.blade.php
@extends('admin.layouts.app')
@section('title','Всички Потребители')

@section('content')
    <div class="card-body  p-0">

        <hr>
        <table class="table table-hover">
            <tbody>
            <tr>
                <th>ID</th>
                <th>дата</th>

                <th>От</th>
                <th>Към</th>
                <th>Тип</th>



                <th>Активна?</th>
                <th>Опции</th>
            </tr>
            @forelse($reputations as $reputation)
                <tr class="{{$reputation->is_active ? '' : 'text-warning'}}">
                    <td>{{$reputation->id}}</td>
                    <td>{{$reputation->created_at}}</td>

                    <td>
                        <a href="{{route('admin.users.edit',$reputation->sender->id)}}"
                           target="_blank">{{$reputation->sender->name}} / {!! $reputation->sender->textrepcount() !!}</a>
                    </td>
                    <td>
                        <a href="{{route('admin.users.edit',$reputation->receiver->id)}}"
                           target="_blank">{{$reputation->receiver->name}}/ {!! $reputation->receiver->textrepcount()
                           !!}</a>
                    </td>

                    @if ($reputation->is_negative)
                        <td>Отрицателна</td>

                    @else
                        <td>Положителна</td>
                    @endif
                    @if ($reputation->is_active)
                        <td>Да</td>

                    @else
                        <td>Не</td>
                    @endif
                    <td>
                        <a href="{{route('admin.reputations.edit', $reputation->id)}}"><button class="btn
                        btn-primary
                        btn-sm">Редакция</button></a>
                        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modal-danger-{{$reputation->id}}">
                            Изтриване
                        </button>
                    </td>
                </tr>
                <div class="modal fade" id="modal-danger-{{$reputation->id}}">
                    <div class="modal-dialog">
                        <div class="modal-content bg-danger">
                            <div class="modal-header">
                                <h4 class="modal-title">Изтриване на Репутация?</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <div class="modal-footer justify-content-between">
                                <form action="{{route('admin.reputations.destroy',$reputation->id)}}" method="POST">
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="btn btn-danger">Изтриване</button>
                                </form>
                                <button type="button" class="btn btn-outline-light" data-dismiss="modal">Отказ</button>
                            </div>
                        </div>
                        <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>

            @empty
                <hr>
                Няма Репутации Все още.
            @endforelse
            </tbody>
        </table>
        <hr>
        {{$reputations->links()}}
    </div>

    <!-- /.modal -->
@stop